### ISSUE TITLE
How to get started with this

### ISSUE THREAD

**Issue by kuashe** [devkitPro/3ds-examples#1]
Hi , any documentation or readme to get started with this ?

**Comment by uschmann** [comment]
Hi,
you need to install the toolchain devkitpro
and devkitARM.
look here:
http://4dsdev.org/thread.php?id=4

**Comment by fincs** [comment]
The instructions posted above are massively outdated. You are better off following [the instructions in the libctru readme](https://github.com/smealum/ctrulib#setup). After running the devkitPro Updater (or the perl script), you should have a copy of the 3DS examples at devkitPro/examples/3ds. Inside there, there is a project template which you can use to develop your homebrew applications.

**Comment by flarn2006** [comment]
@fincs You could at least answer his question :/
