### ISSUE TITLE
graphics\gpu\geoshader build error

### ISSUE THREAD

**Issue by quizque** [devkitPro/3ds-examples#14]
While running make on all the examples, the geoshader example gave me an error

https://gist.github.com/nickthegamer5/8c2e0e5af596681829a172c52e3abc6a

I have Citro, the newest ctrulib and devkitarm

**Comment by fincs** [comment]
The latest version of picasso (which currently does not ship with devkitARM) is required.

**Comment by WinterMute** [comment]
No you don't.

Compiling things from git won't work with stable releases
