### ISSUE TITLE
mingw32-make errors

### ISSUE THREAD

**Issue by ghost** [devkitPro/3ds-examples#23]
Errors:
mingw32-make[1]: Entering directory 'C:/dka/examples/3ds/app_launch'
Makefile:10: C:dka/devkitARM/3ds_rules: No such file or directory
mingw32-make[1]: *** No rule to make target 'C:dka/devkitARM/3ds_rules'.  Stop.
mingw32-make[1]: Leaving directory 'C:/dka/examples/3ds/app_launch'
Makefile:13: recipe for target 'examples' failed
mingw32-make: *** [examples] Error 1

**Comment by fincs** [comment]
Why are you using "mingw32-make"? You should only use the version of make provided with devkitPro-msys (or msys2 if you have that installed).

**Comment by valentinvanelslande** [comment]
i use msys2
![ ](https://user-images.githubusercontent.com/22228082/35448504-18d6500e-0280-11e8-906e-bf2e5300e0d0.PNG)
