### ISSUE TITLE
Missing header

### ISSUE THREAD

**Issue by MarcoMartins86** [devkitPro/3ds-examples#27]
Is not really that relevant but there's a missing header. All other examples compiled successfully.

3ds/graphics/bitmap/24bit-color/source/main.c:20:10: fatal error: brew_bgr.h: No such file or directory
 #include "brew_bgr.h"

**Comment by skibur** [comment]
I just noticed the missing header file right now.

**Comment by oreo639** [comment]
Works for me. Make sure you have imagemagick installed, although in most scenarios it would probably be better to use citro2d (gpusprites example).

Edit: Reply to a comment who the poster seems to have deleted.
