### ISSUE TITLE
3ds-examples/audio/mic not working

### ISSUE THREAD

**Issue by badda71** [devkitPro/3ds-examples#30]
The microphone example in 3ds-examples/audio/mic is not working on my N3DS (B9S w/ luma 10.0.1). Compiles and runs fine but no audio is recorded and/or played - only silence. Can anyone confirm this working on the above config?

**Comment by WinterMute** [comment]
This is working fine for me on the same setup. Recordings can be quite quiet though so check with the volume up full.

**Comment by badda71** [comment]
I compiled again and tested - it actually does work. No idea what I did wrong ...
