### ISSUE TITLE
Examples that use the DSP are broken.

### ISSUE THREAD

**Issue by ghost** [devkitPro/3ds-examples#36]
From the audio folder, the opus-decoding, filter, and streaming examples are broken for me. They produce no sound. Only the mic example is working, which uses CSND instead of the DSP. I have an N3DS, and the built 3dsx files are started from HBL version 2.1.0

**Comment by fincs** [comment]
Make sure you have dspfirm.cdc in the 3ds folder inside your SD card. DSP cannot function without it.

**Comment by ghost** [comment]
Whoops. Thank you
