### ISSUE TITLE
problems with 3ds building files

### ISSUE THREAD

**Issue by Emayeah** [devkitPro/3ds-examples#42]
one day i downloaded a project, i modified it and BOUM devkitpro won't make me the file (3dsx). the project is koopa cruiser, i don't know how to fix it :/
[KoopaCruiser-0.5.zip](https://github.com/devkitPro/3ds-examples/files/7797510/KoopaCruiser-0.5.zip)
:( someone can help me? even without modifying the source code i can't build the file.

**Comment by oreo639** [comment]
Why do you specifically need to build KoopaCruiser?
As the readme for that repo states If you want is an example of downloading using HTTP:C (which is basically all it does) just use this:
https://github.com/devkitPro/3ds-examples/tree/master/network/http/

**Comment by Emayeah** [comment]
i need to build koopa cruiser for trying to modify the default url

**Comment by thejsa** [comment]
Hi @Emayeah -- this is a *really* old project and it's not really a good example to be using today anyway; this was something I explored when I was young and naive 🙈

If it doesn't build anymore, that isn't surprising, considering the code dates back to some much earlier days of 3DS homebrew, when libctru was less mature and APIs were different.

That repo for 'Koopa Cruiser' really doesn't have any interesting functionality over the HTTP:C example -- as I see @Oreo639 has already explained. As such, if you're interested in building a homebrew web browser my ancient project isn't a good starting point I'm afraid.

(With all this said -- I might have another go at building a homebrew web browser *properly* this year if I have time, with the benefit of more experience.)

I noticed also in your GitHub bio you say "i don't know literally nothing of hb coding i know a little of c" -- a web browser, whilst exciting, is quite a complicated thing to start working on as a first homebrew project (if I understand correctly). You'd probably want to spend some time working on simpler homebrew projects first to get a feel for the way things work.

(Also, although not homebrew-related as such, if you're curious about building an *actual* toy web browser, a really good resource is https://browser.engineering/ and you might enjoy that! It takes you through doing that in Python on a standard computer.)

**Comment by Emayeah** [comment]
oh... thank you very much!!!

**Comment by Emayeah** [comment]
> (With all this said -- I might have another go at building a homebrew web browser properly this year if I have time, with the benefit of more experience.)

that.. didn't happen. D: (think about the fact that when i opened the issue i was almost 13... at least now i am more mature, i am 14) but i still have interest in programming, next school year i will go to a school where you learn programming forgor how it's called sorry even in italian (my main language). maybe when i have more experience on the 3ds and the httpc library i could start doing my own version, afterall i am 132 iq in logic (no flex). <3
