### ISSUE TITLE
SSLC demo fails to connect

### ISSUE THREAD

**Issue by SirFluffDev** [devkitPro/3ds-examples#51]
Once running on the 3DS, the console log shows this:
`"ssclStartConnection() failed: 0xd8a0b814"`

According to 3dbrew, this error translates to
`"Server cert verification failed since the RootCA isn't trusted".`

I could be wrong, but I believe this means that the `builtin_rootca.der` file needs to be updated.
If I am doing something wrong, and there is a way to fix this myself, please let me know.

**Comment by yellows8** [comment]
libcurl should really be used instead - even with the proper rootCA 3DS TLS is outdated.

**Comment by SirFluffDev** [comment]
Can you link me some resources related to this libcurl? I've heard it mentioned before, but for some reason can't seem to find it google...

Sorry if I'm missing something.

**Comment by yellows8** [comment]
https://github.com/devkitPro/3ds-examples/issues/49#issuecomment-1120525605

**Comment by SirFluffDev** [comment]
Alright, thanks!

Do I still need to try and link a new RootCA, or does libcurl handle that for me? It was my understanding that in order to connect to HTTPS that I needed to make a TLS connection, although my knowledge of such things is very basic.

I'm trying to make a simple POST request to the Discord API if that changes anything.

**Comment by yellows8** [comment]
Yeah you'd specify rootCA(s) with curl setopt.

**Comment by SirFluffDev** [comment]
Okay, I've properly got libcurl setup. I've been stuck on this for longer than I'd like to admit... Thank you so much for your help!
