### ISSUE TITLE
opus audio decoder does not work on citra

### ISSUE THREAD

**Issue by AAM1075** [devkitPro/3ds-examples#52]
opus audio decoder does not work on citra, but does work on a real 3DS

**Comment by fincs** [comment]
[Sounds like you might want to report this issue to Citra](https://github.com/citra-emu/citra/issues). Since it works on a real 3DS, there is no bug at our side.

**Comment by TurtleP** [comment]
@MEMESCOEP it's likely that you're missing your dspfirm.cdc on the emulated sd card. Last I checked, you don't need to use the actual dumped file, but simply creating a new empty file with the proper name and extension should work. If it doesn't, then use your dumped file from your own 3DS.

**Comment by AAM1075** [comment]
Ohhh ok. Thanks for the information!
I'll try that now

**Comment by AAM1075** [comment]
hmmm. @TurtleP it doesn't seem to be working with the empty file, when I get home I'll dump from the 3ds

**Comment by TurtleP** [comment]
Did you place it in the correct directory? I believe it should be under `sdmc:/3DS`.

**Comment by AAM1075** [comment]
ohhh well no I didn't then. I had put it on the root
EDIT: @TurtleP that doesn't work either

**Comment by FomariTheSonicRipoff** [comment]
I think you need to add it to sdmc/3ds  and also (for me atleast) i needed to put the dumped file from the 3ds.
It crashed when it had the empty file
