### ISSUE TITLE
3ds.h Missing

### ISSUE THREAD

**Issue by DotJARgon** [devkitPro/3ds-examples#54]
Hello! I was attempting to compile a couple of examples, however during the compile process I ran into an issue with the make process!

```
A:\3dsprojects\3ds-examples\graphics\gpu\textured_cube>make
main.c
A:/3dsprojects/3ds-examples/graphics/gpu/textured_cube/source/main.c:1:10: fatal error: 3ds.h: No such file or directory
    1 | #include <3ds.h>
      |          ^~~~~~~
compilation terminated.
make[1]: *** [/opt/devkitpro/devkitARM/base_rules:85: main.o] Error 1
make: *** [Makefile:165: all] Error 2

A:\3dsprojects\3ds-examples\graphics\gpu\textured_cube>
```

I believe I have the library paths set up correctly (I installed devkitPro software) and my paths for those are as follows:

![devk](https://user-images.githubusercontent.com/55509271/216752056-f4ed38c1-ee39-4ef8-83f8-3c578f9c5259.PNG)

where my A: drive is where I installed devkitPro software, if I am misunderstanding something please let me know!

**Comment by oreo639** [comment]
The paths should be `/opt/devkitpro` (regardless of what hard drive you installed it to), did you change it?

**Comment by DotJARgon** [comment]
Oh yeah I did! My bad there! I had changed it for a different project (smealum's 3dscraft), thank you for pointing that out, I think I have it working now, I got an error about a png not being able to be loaded? But when I ran the make command a second time it seems to have worked fine.

**Comment by fincs** [comment]
The `CTRULIB` environment variable does not actually exist, nor is it needed for a functional toolchain installation.
