### ISSUE TITLE
not being able to compile the physics example

### ISSUE THREAD

**Issue by nahiassis** [devkitPro/3ds-examples#56]
i can't compile the box2d example due to it being missing on the lib folder in the libctru folder
what is a working way to install the box2d lib
and if this isn't the correct repo for me to ask for this
please say what would be the one

**Comment by WinterMute** [comment]
All the libraries we distribute can be found in pacman, how you get them depends slightly on your host system. On windows open an msys2 terminal then type `pacman -S 3ds-box2d` if it's an arch derivative linux use `sudo pacman -S 3ds-box2d` for systems where dkp-pacman has been installed then it's `sudo dkp-pacman -S 3ds-box2d`
