### ISSUE TITLE
Missing file brew_bgr.h in graphics/bitmap/24bit-color

### ISSUE THREAD

**Issue by kry008** [devkitPro/3ds-examples#58]
https://github.com/devkitPro/3ds-examples/blob/ee2e047049f6962a1deab26779e66f521302ab02/graphics/bitmap/24bit-color/source/main.c#L20

There is missing header file brew_bgr.h in graphics/bitmap/24bit-color

**Comment by WinterMute** [comment]
No there isn't. This header is generated.
