### ISSUE TITLE
modplug-decoding example doesn't work correctly

### ISSUE THREAD

**Issue by camthehaxman** [devkitPro/3ds-examples#59]
## Bug Report

I'm having trouble getting stable audio playback in a game I'm working on, so I decided to look at the examples for guidance. I could not find a sample file that was compatible with the opus-decoding example, but the modplug-decoding example comes with one, so I tried that.

### How can the issue be reproduced?

1. Compile the modplug-decoding example.
2. Copy the modplug-decoding.3dsx anywhere on the 3DS SD card, and copy the space_debris.mod file to the root of the SD card.
3. Open the Homebrew Launcher and use it to launch the modplug-decoding example.
4. The sound will play for about 2 seconds, then suddenly cut out.

### Environment?

Void Linux x86_64
#### Relevant packages installed:
3ds-cmake 1.5.1-1
3ds-examples 20230610-1
3ds-libmodplug 0.8.9.0-1
3ds-libogg 1.3.4-2
3ds-libopus 1.3-1
3ds-libvorbisidec 1.2.1-3
3ds-opusfile 0.11-1
3ds-pkg-config 0.28-5
3ds-zlib 1.3-1
3dslink 0.6.2-1
3dstools 1.3.1-2
armv4t-pkg-config 0.28-1
citro2d 1.6.0-1
citro3d 1.7.1-2
devkit-env 1.0.1-2
devkitARM r62-1
devkitARM-gdb 13.2-1
devkitPPC r44.2-2
devkitPPC-gdb 13.2-1
devkitarm-cmake 1.2.2-1
devkitarm-crtls 1.2.3-1
devkitarm-rules 1.5.1-1
devkitpro-keyring 20180316-1
dkp-cmake-common-utils 1.5.2-1
general-tools 1.4.4-1
grit 0.9.2-1
libctru 2.3.1-1
libogc 2.5.0-2
mmutil 1.10.1-1
picasso 2.7.2-2
ppc-pkg-config 0.28-5
tex3ds 2.3.0-3

**Comment by oreo639** [comment]
Thank you for reporting, I can reproduce the issue.

> and copy the space_debris.mod file to the root of the SD card.

This isn't necessary as the file gets loaded from the embedded romfs.

>  I could not find a sample file that was compatible with the opus-decoding example

The opus example comes with a sample file.

**Comment by camthehaxman** [comment]
Confirmed that #60 fixes it on my end as well. Thank you very much!
