### ISSUE TITLE
Errors building 3ds examples on MacOS

### ISSUE THREAD

**Issue by deReeperJosh** [devkitPro/3ds-examples#62]
### What's the issue you encountered?

On a fairly fresh MacOS machine, when trying to build 3ds examples (and other 3ds programs) I get an error linking:

/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/14.1.0/../../../../arm-none-eabi/bin/ld: /opt/devkitpro/devkitARM/bin/../libexec/gcc/arm-none-eabi/14.1.0/liblto_plugin.so: error loading plugin: dlsym(0x933e2050, _onload): symbol not found

### Environment?

MacOS 14.4.1, xcode command line tools 15.3

Works fine when building on my Asahi Fedora install

**Comment by WinterMute** [comment]
Not a 3DS examples issue. Problems that don't clearly relate to a particular repo should generally be directed to the forums. This issue was raised at https://devkitpro.org/viewtopic.php?t=9583
