### ISSUE TITLE
24bit-color distorts image

### ISSUE THREAD

**Issue by PaxtonPenguin** [devkitPro/3ds-examples#63]
### What's the issue you encountered?
the image: ![512chaz](https://github.com/devkitPro/3ds-examples/assets/84253355/4c9b46e0-2d3b-446d-bd40-98dc03210426)
gets distorted so you can't see it, well you can, but it looks like this: ![20240609_073018](https://github.com/devkitPro/3ds-examples/assets/84253355/4669384a-bf39-4e80-8117-b3e5099bd736)

### How can the issue be reproduced?
changing the brew.png image to this image
### Environment?
downloaded from website, that's it

i have to use the cmd because msys wont detect convert as coming from imagemagick, instead it comes from System32 (god i hate windows 11)
### Additional context?

- Additional info about your environment:
devkitpro's msys2 overwrited the cmd, so now i can type uname into cmd

**Comment by fincs** [comment]
The image needs to be 320x240, not any arbitrary resolution. Are you sure your image is 320x240?

**Comment by PaxtonPenguin** [comment]
it isnt, thanks
