### ISSUE TITLE
building a cia file might be helpful

### ISSUE THREAD

**Issue by PaxtonPenguin** [devkitPro/3ds-examples#64]
#### Overview:
a way to build as a cia file, not a 3dsx file

### Why would this feature be useful?
so people could load it faster without loading the hombrew launcher

**Comment by fincs** [comment]
3DSX is the sole supported format for homebrew applications. CIA is a format for installable pirated games. Piracy is not supported.

**Comment by PaxtonPenguin** [comment]
have you seen what's on universal-updater (software store thing), most of it is .cia files, and none of them are pirated games. few things on universal-updater (as well as the ports of games i found) are 3dsx only. the first thing on the forum post for cxitool (which didn't work) is: "This can be very useful for instances where the 3dsx author has chosen not to provide a cia, and has the source code closed (or too difficult to compile). A lot of older 3dsx homebrew has suffered this fate and this app could be of great benefit to making them more accessible to a new audience."

**Comment by PaxtonPenguin** [comment]
nvm, cxitool worked
