### ISSUE TITLE
Undefined reference errors when running `make`

### ISSUE THREAD

**Issue by flarn2006** [devkitPro/3ds-examples#8]
Yes, I just updated libctru to the latest version from Github. And previously I tested it on the latest _release_ version, which didn't work either.

Here's what happens when I try to compile it:

```
D:\Users\Flarn\Desktop\3DS_stuff\3ds-examples-master>make
make[1]: Entering directory `/d/Users/Flarn/Desktop/3DS_stuff/3ds-examples-master/app_launch'
linking app_launch.elf
main.o: In function `main':
d:/Users/Flarn/Desktop/3DS_stuff/3ds-examples-master/app_launch/source/main.c:30: undefined reference to `aptOpenSession'
d:/Users/Flarn/Desktop/3DS_stuff/3ds-examples-master/app_launch/source/main.c:32: undefined reference to `APT_PrepareToDoAppJump'
d:/Users/Flarn/Desktop/3DS_stuff/3ds-examples-master/app_launch/source/main.c:34: undefined reference to `APT_DoAppJump'
d:/Users/Flarn/Desktop/3DS_stuff/3ds-examples-master/app_launch/source/main.c:36: undefined reference to `aptCloseSession'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [/d/Users/Flarn/Desktop/3DS_stuff/3ds-examples-master/app_launch/app_launch.elf] Error 1
make[1]: *** [build] Error 2
make[1]: Leaving directory `/d/Users/Flarn/Desktop/3DS_stuff/3ds-examples-master/app_launch'
make: *** [examples] Error 1

D:\Users\Flarn\Desktop\3DS_stuff\3ds-examples-master>_
```

**Comment by fincs** [comment]
Yeah, currently some examples are broken due to APT changes. As soon as I finish the APT refactor I'll fix the examples. In the meantime just get rid of calls to aptOpenSession/aptCloseSession and change AppJump to ApplicationJump.

**Comment by Jolty95** [comment]
Any news about this "bug"?
Or solution :)
Thanks!

**Comment by flarn2006** [comment]
@Jolty95 Seems like it works now, but I recently formatted my hard drive and installed Linux, so my configuration is very different now.

**Comment by Jolty95** [comment]
@flarn2006  Thanks for answering :)
And tested, it works perfectly!!
Thanks! 👍 

EDIT: Can't launch non-system cias. Always get a prefetch abort (svcbreak) exception

**Comment by profi200** [comment]
"non-system cias" which is? What did you test? Keep in mind title IDs are different per region for non-system titles too.

**Comment by Jolty95** [comment]
@profi200  
Thanks for answering. When I wrote that some examples had problems due to APT changes so now I should work all as it should.
The problem I had if I remember correctly, is that if I modify the example to run a app (example was camera), console crash and get a prefetch abort exception. Now it should work, so if you don't mind you can close this issue
Thanks :)

**Comment by profi200** [comment]
It is already closed. Also a little side note: In the example i passed empty buffers but later i noticed NULL works too. So unless you need to pass params no need for the empty buffers.
